workflows:
  android-build:
    name: Android Build Workflow
    android:
      # تحديد إصدار Android SDK
      sdk: stable
      build:
        # تحديد الأوامر الخاصة بالبناء
        commands:
          - flutter pub get
          - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
