workflows:
  android-build:
    name: Android Build Workflow
    flutter:
      version: stable
    build:
      android:
        # يمكنك إضافة إعدادات البناء هنا، مثل تحديد إصدار SDK إذا لزم الأمر
        gradle:
          version: 7.0
        commands:
          - flutter pub get
          - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
